### ISSUE TITLE
Update sockso-optionals.zip

### ISSUE THREAD

**Issue by nowotny** [rodnaph/sockso-website#10]
Hello.

Lately you updated the mysql driver but sockso-optionals.zip that's linked here: http://sockso.pu-gh.com/manual/optionals.html still contains the old version that does not work with Sockso 1.5.1. 

Please update the mysql driver in sockso-optionals.zip.

Thanks

**Comment by rodnaph** [comment]
I've updated it with optionals built from latest master - thanks for the reminder!  :D
