### ISSUE TITLE
The server is not picking up the MP3 tags.

### ISSUE THREAD

**Issue by xcarnage** [rodnaph/sockso-website#15]
Where the cover is just says cover not found. Every other program that reads tags picks them up. Are you still currently bug fixing? I'm running Win10. The program is great, Thanks for the development.

**Comment by rodnaph** [comment]
Hi - I'm afraid I don't have time to support this project any more.

You may want to file this issue on the Sockso project though incase someone else can pick it up...  https://github.com/rodnaph/sockso

Thanks
