### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by nperrier** [rodnaph/sockso-website#9]
http://sockso.pu-gh.com/manual/comments/artwork.html

uh oh!

**Comment by rodnaph** [comment]
Thanks, where did this link come from?

**Comment by nperrier** [comment]
http://sockso.pu-gh.com/

bottom of the front page under "Manual" -> "Cover Art"

**Comment by rodnaph** [comment]
Thanks!

On 28 January 2012 01:37, Nathan <
reply@reply.github.com
